services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - certificate_media:/app/media
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: change-me-in-docker
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: certificates
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config.celery worker --loglevel=INFO
    volumes:
      - .:/app
      - certificate_media:/app/media
    environment:
      SECRET_KEY: change-me-in-docker
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: certificates
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: certificates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
  certificate_media:
